objects/Account.object
<CustomObject>
    <fields>
        <fullName>AE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AE</label>
        <referenceTo>AE__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APOAccountId__c</fullName>
        <label>APOAccountId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APOAccountOwner__c</fullName>
        <label>APOAccountOwner</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APOContractId__c</fullName>
        <label>APOContractId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_Source__c</fullName>
        <label>Created Source</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <formula>$Label.CopadoDomain &amp; &quot;/lightning/r/Account/&quot; &amp;  APOAccountId__c &amp; &quot;/view&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>URL</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AE__c.object
<CustomObject>
    <fields>
        <fullName>APOid__c</fullName>
        <label>APOid</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <label>Manager</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>AE</label>
    <nameField>
        <label>AE Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AEs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Link__c.object
<CustomObject>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>Link</label>
    <nameField>
        <label>Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opp__c.object
<CustomObject>
    <fields>
        <fullName>AE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AE</label>
        <referenceTo>AE__c</referenceTo>
        <relationshipLabel>Opps</relationshipLabel>
        <relationshipName>Opps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>APOAccountId__c</fullName>
        <label>APOAccountId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APOAccountName__c</fullName>
        <label>APOAccountName</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opps</relationshipLabel>
        <relationshipName>Opps2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <formula>$Label.CopadoDomain &amp; &quot;/lightning/r/Opportunity/&quot; &amp;   APOOppId__c  &amp; &quot;/view&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>URL</label>
        <type>Text</type>
    </fields>
    <label>Opp</label>
    <nameField>
        <label>Opp Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OppRow__c.object
<CustomObject>
    <fields>
        <fullName>APOAccountId__c</fullName>
        <label>APOAccountId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APOAccountName__c</fullName>
        <label>APOAccountName</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Opps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MonthlyString__c</fullName>
        <formula>IF( Monthly__c  &lt; 0, &quot;(&quot;, &quot;&quot;) &amp; &quot;$&quot; &amp;
IF(ABS(Monthly__c) &gt;= 1000000, TEXT(FLOOR(ABS(Monthly__c) / 1000000)) &amp; &quot;,&quot;, &quot;&quot;) &amp;
IF(ABS(Monthly__c) &gt;= 1000, RIGHT(TEXT(FLOOR(ABS(Monthly__c) / 1000)), 3) &amp; &quot;,&quot;, &quot;&quot;) &amp;
RIGHT(TEXT(FLOOR(ABS(Monthly__c))), 3) &amp;

IF(Monthly__c &lt; 0, &quot;)&quot;, &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MonthlyString</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Monthly__c</fullName>
        <label>Monthly</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>QuantityString__c</fullName>
        <formula>IF( Quantity__c &lt; 0, &quot;(&quot;, &quot;&quot;) &amp;
IF(ABS(Quantity__c) &gt;= 1000000, TEXT(FLOOR(ABS(Quantity__c) / 1000000)) &amp; &quot;,&quot;, &quot;&quot;) &amp;
IF(ABS(Quantity__c) &gt;= 1000, RIGHT(TEXT(FLOOR(ABS(Quantity__c) / 1000)), 3) &amp; &quot;,&quot;, &quot;&quot;) &amp;
RIGHT(TEXT(FLOOR(ABS(Quantity__c))), 3) &amp;

IF(Quantity__c &lt; 0, &quot;)&quot;, &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>QuantityString</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalString__c</fullName>
        <formula>IF(Total__c &lt; 0, &quot;(&quot;, &quot;&quot;) &amp; &quot;$&quot; &amp;
IF(ABS(Total__c) &gt;= 1000000, TEXT(FLOOR(ABS(Total__c) / 1000000)) &amp; &quot;,&quot;, &quot;&quot;) &amp;
IF(ABS(Total__c) &gt;= 1000, RIGHT(TEXT(FLOOR(ABS(Total__c) / 1000)), 3) &amp; &quot;,&quot;, &quot;&quot;) &amp;
RIGHT(TEXT(FLOOR(ABS(Total__c))), 3) &amp; 

IF(Total__c &lt; 0, &quot;)&quot;, &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TotalString</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>OppRow</label>
    <nameField>
        <displayFormat>OR-{0000}</displayFormat>
        <label>Opp Row</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OppRows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Subscription__c.object
<CustomObject>
    <fields>
        <fullName>APOAccountId__c</fullName>
        <label>APOAccountId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APOAccountName__c</fullName>
        <label>APOAccountName</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APOAccountOwnerManager__c</fullName>
        <label>APOAccountOwnerManager</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APOAccountOwner__c</fullName>
        <label>APOAccountOwner</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APOContractId__c</fullName>
        <label>APOContractId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APOSubscriptionId__c</fullName>
        <label>APOSubscriptionId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APOcontractURL__c</fullName>
        <formula>$Label.CopadoDomain &amp; &quot;/lightning/r/Contract/&quot; &amp;  APOContractId__c  &amp; &quot;/view&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>APOcontractURL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContractEndString__c</fullName>
        <formula>TEXT(Month(  Contract_End__c  )) &amp; &quot;/&quot; &amp; TEXT(DAY( Contract_End__c )) &amp; &quot;/&quot; &amp; TEXT(YEAR( Contract_End__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ContractEndString</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContractStartString__c</fullName>
        <formula>TEXT(Month( Contract_Start__c )) &amp; &quot;/&quot; &amp; TEXT(DAY( Contract_Start__c )) &amp; &quot;/&quot; &amp; TEXT(YEAR( Contract_Start__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ContractStartString</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_End__c</fullName>
        <label>Contract End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Start__c</fullName>
        <label>Contract Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Term__c</fullName>
        <label>Contract Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EndString__c</fullName>
        <formula>TEXT(Month(End__c)) &amp; &quot;/&quot; &amp; TEXT(DAY( End__c )) &amp; &quot;/&quot; &amp; RIGHT(TEXT(YEAR( End__c )), 2)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EndString</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End__c</fullName>
        <label>End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MonthlyString__c</fullName>
        <formula>IF( Monthly__c  &lt; 0, &quot;(&quot;, &quot;&quot;) &amp; &quot;$&quot; &amp;
IF(ABS(Monthly__c) &gt;= 1000000, TEXT(FLOOR(ABS(Monthly__c) / 1000000)) &amp; &quot;,&quot;, &quot;&quot;) &amp;
IF(ABS(Monthly__c) &gt;= 1000, RIGHT(TEXT(FLOOR(ABS(Monthly__c) / 1000)), 3) &amp; &quot;,&quot;, &quot;&quot;) &amp;
RIGHT(TEXT(FLOOR(ABS(Monthly__c))), 3) &amp;

IF(Monthly__c &lt; 0, &quot;)&quot;, &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MonthlyString</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Monthly__c</fullName>
        <label>Monthly</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PurchaseString__c</fullName>
        <formula>IF(  Purchase_Price__c   &lt; 0, &quot;(&quot;, &quot;&quot;) &amp; &quot;$&quot; &amp;
IF(ABS(Purchase_Price__c) &gt;= 1000000, TEXT(FLOOR(ABS(Purchase_Price__c) / 1000000)) &amp; &quot;,&quot;, &quot;&quot;) &amp;
IF(ABS(Purchase_Price__c) &gt;= 1000, RIGHT(TEXT(FLOOR(ABS(Purchase_Price__c) / 1000)), 3) &amp; &quot;,&quot;, &quot;&quot;) &amp;
RIGHT(TEXT(FLOOR(ABS(Purchase_Price__c))), 3) &amp;

IF(Purchase_Price__c &lt; 0, &quot;)&quot;, &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PurchaseString</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purchase_Price__c</fullName>
        <label>Purchase Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>QuantityString__c</fullName>
        <formula>IF( Quantity__c  &lt; 0, &quot;(&quot;, &quot;&quot;)  &amp;
IF(ABS(Quantity__c) &gt;= 1000000, TEXT(FLOOR(ABS(Quantity__c) / 1000000)) &amp; &quot;,&quot;, &quot;&quot;) &amp;
IF(ABS(Quantity__c) &gt;= 1000, RIGHT(TEXT(FLOOR(ABS(Quantity__c) / 1000)), 3) &amp; &quot;,&quot;, &quot;&quot;) &amp;
RIGHT(TEXT(FLOOR(ABS(Quantity__c))), 3) &amp;

IF(Quantity__c &lt; 0, &quot;)&quot;, &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>QuantityString</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StartString__c</fullName>
        <formula>TEXT(Month(Start__c))  &amp; &quot;/&quot; &amp;  TEXT(DAY( Start__c )) &amp; &quot;/&quot; &amp; TEXT(YEAR( Start__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>StartString</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <label>Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TotalString__c</fullName>
        <formula>IF(Total__c &lt; 0, &quot;(&quot;, &quot;&quot;) &amp; &quot;$&quot; &amp;
IF(ABS(Total__c) &gt;= 1000000, TEXT(FLOOR(ABS(Total__c) / 1000000)) &amp; &quot;,&quot;, &quot;&quot;) &amp;
IF(ABS(Total__c) &gt;= 1000, RIGHT(TEXT(FLOOR(ABS(Total__c) / 1000)), 3) &amp; &quot;,&quot;, &quot;&quot;) &amp;
RIGHT(TEXT(FLOOR(ABS(Total__c))), 3) &amp; 

IF(Total__c &lt; 0, &quot;)&quot;, &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TotalString</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Service</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/findLinks.cls
public with sharing class findLinks {
    
    @AuraEnabled(cacheable=true) 
    public static LIST<AE__c> getAEs() {
        LIST<AE__c> AEs = [SELECT id, Name, Region__c, Manager__c, APOid__c, Created_Source__c
                           FROM AE__c 
                           WHERE Active__c=true
                           ORDER BY Name];
       return AEs;
    }

    @AuraEnabled(cacheable=true) 
    public static LIST<Account> getAccounts(id aeId) {
        LIST<Account> Accounts = [SELECT id, Name, Type, URL__c, APOAccountOwner__c,
                                Created_Source__c // AE__c, AE__r.id, 
                           FROM Account 
                           WHERE AE__r.id = :aeId
                           ORDER BY Name];
       return Accounts;
    }

    @AuraEnabled(cacheable=true) 
    public static LIST<Subscription__c> getSubscriptions(id accountId) {
        LIST<Subscription__c> Subscriptions = [SELECT id, Name, 
                                               Account__c, APOAccountId__c, APOAccountName__c,
                                               APOSubscriptionId__c, APOContractId__c, APOcontractURL__c, 
                                               APOAccountOwner__c, APOAccountOwnerManager__c,
                                               Quantity__c, QuantityString__c, Total__c, TotalString__c,
                                               Purchase_Price__c, PurchaseString__c,
                                               // Monthly__c, MonthlyString__c, 
                                               End__c, EndString__c, Start__c, StartString__c,
                                               Contract_End__c, Contract_Start__c, ContractEndString__c, ContractStartString__c,
                                               Contract_Term__c,
                                               Processed__c, ProcessedCreate__c, ProcessedAccountJoin__c
                           FROM Subscription__c 
                           WHERE Account__c = :accountId  // account id in this Salesforce, not APO's
                           ORDER BY Name ];
       return Subscriptions;
    }

    @AuraEnabled(cacheable=true) 
    public static LIST<Opp__c> getOpps(id accountId) {
        LIST<Opp__c> Opps = [SELECT id, Name,
                                Account__c, AE__c,
                                ACV_APO__c, ACV_APOString__c, ACVcalculated__c, Amount__c, AmountString__c,
                                APOAccountId__c, APOAccountName__c,
                                APOOppId__c, URL__c,
                                Close_Date__c, CloseString__c,
                                Forecast__c, Stage__c, Type__c,
                                Owner_Name__c
                           FROM Opp__c 
                           WHERE Account__c = :accountId  // account id in this Salesforce, not APO's
                           ORDER BY Name ];
       return Opps;
    } 

    @AuraEnabled(cacheable=true) 
    public static LIST<OppRow__c> getOppRows(id oppSelectedId) {
        LIST<OppRow__c> OppRows = [SELECT id, Name, 
                                Account__c, APOAccountId__c, APOAccountName__c, Account_Type__c,
                                ACV_APO__c, ACV_APOString__c, ACVcalculated__c, Amount__c,
                                Opportunity_Name__c, Opp__c, APOOppId__c,
                                Account_Owner__c, Account_Manager__c,
                                Owner_Name__c, 
                                Close_Date__c, CloseString__c,
                                Forecast__c, Stage__c, Type__c,
                                Product__c, Quantity__c, QuantityString__c, // Monthly__c, MonthlyString__c,
                                Sales_Price__c, SalesPriceString__c,
                                Total__c, TotalString__c
                                // Product_Code__c, Owner_Role__c, Next_Step__c
                           FROM OppRow__c 
                           WHERE Opp__c = :oppSelectedId  // oppSelectedId id in this Salesforce, not APO's
                           ORDER BY Name ];
       return OppRows;
    }


    @AuraEnabled(cacheable=true) 
    public static LIST<link__c> getLinks(string searchValue, boolean allCheck, string valueOfSelectedType) {

        string whereValue = '%' + searchValue + '%';
        string excludeArchive = ' AND Archived__c = False ';  if (allCheck) excludeArchive = ' ';

        string filterByType = '';
        if (valueOfSelectedType==null || valueOfSelectedType=='' || valueOfSelectedType=='--none--') filterByType = ''; // do nothing
        else filterByType = ' AND Type__c=\'' + valueOfSelectedType + '\''; // + valueOfSelectedType + '\' ';

        String q = 'SELECT id, Name, Details__c, URL__c, Type__c, EditLink__c, Archived__c ' + 
                    ' FROM Link__c ' +
                    ' WHERE name like :whereValue ' +
                    excludeArchive +
                    filterByType +
                    ' ORDER BY Name ';
        
        /*
        LIST<link__c> links = [SELECT id, Name, Details__c, URL__c, Type__c, EditLink__c, Archived__c
                               FROM Link__c 
                               WHERE name like :whereValue 
                               ORDER BY Type__c asc, Name];
        */ 

        // system.debug(q); 
        LIST<link__c> links = Database.query(q);

        return links;
    }
}