objects/AE__c.object
<CustomObject>
    <label>AE</label>
    <nameField>
        <label>AE Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AEs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OppRow__c.object
<CustomObject>
    <fields>
        <fullName>APOAccountId__c</fullName>
        <label>APOAccountId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APOAccountName__c</fullName>
        <label>APOAccountName</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APOOppId__c</fullName>
        <label>APOOppId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <label>Account Manager</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <label>Account Owner</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <label>Opportunity Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_Name__c</fullName>
        <label>Owner Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>OppRow</label>
    <nameField>
        <displayFormat>OR-{0000}</displayFormat>
        <label>Opp Row</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OppRows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Subscription__c.object
<CustomObject>
    <fields>
        <fullName>APOAccountId__c</fullName>
        <label>APOAccountId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APOAccountName__c</fullName>
        <label>APOAccountName</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APOAccountOwnerManager__c</fullName>
        <label>APOAccountOwnerManager</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APOAccountOwner__c</fullName>
        <label>APOAccountOwner</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APOContractId__c</fullName>
        <label>APOContractId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APOSubscriptionId__c</fullName>
        <label>APOSubscriptionId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Service</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/toolsControllerTest.cls
@isTest

private class toolsControllerTest {
   
    static testMethod void runOppRows() {

        OppRow__c opprow = new OppRow__c();
        opprow.APOAccountId__c = '0015p00005YKzcl';
        opprow.APOAccountName__c = 'AccountName';
        opprow.Account_Type__c = 'Type';
        opprow.Opportunity_Name__c = 'Opportunity_Name';
        opprow.APOOppId__c = '0065p000013B60j';
        opprow.Account_Owner__c = 'Account_Owner';
        opprow.Account_Manager__c = 'Account_Manager';
        opprow.Owner_Name__c = 'Owner_Name';
        insert opprow;
        
        Subscription__c sub = new Subscription__c();
        sub.Name = 'Name'; 
        sub.APOAccountId__c = '0015p00005YKzcl';
        sub.APOAccountName__c  = 'AccountName';
        sub.APOSubscriptionId__c = 'aDV5p000000wlM4';
        sub.APOContractId__c = '8005p00000FOxAM';
        sub.APOAccountOwner__c = 'Account_Owner';
        sub.APOAccountOwnerManager__c = 'Account_Manager';
        insert sub;

        AE__c ae = new AE__c();
        ae.Name = 'Account_Owner';
        insert ae;

        toolsController TC = new toolsController();
        // TC.toolsController();
        TC.LoadOppRows();
        TC.LoadAEs();
        TC.LoadAccounts();
        TC.LoadOpps();
        TC.LoadSubscriptions();

        TC.deleteAllAEs();
        TC.CreateAEsFromRows();
        TC.deleteAllAccounts();
        TC.CreateAccountsFromRows();
        TC.deleteAllOpps();
        TC.CreateOppsFromRows();
        TC.deleteAllOppRows();
        TC.joinOppRowsToOpps();
        TC.clearOppRowProcessed();

        TC.createAEsFromSubscriptions();
        TC.createAccountsFromSubscriptions();
        TC.joinSubscriptionsToAccounts();
        TC.deleteAllSubscriptions();
        TC.joinAccountsToAEs();
        TC.clearSubscriptionsProcessed();
        

    }
}