objects/Check_List__c.object
<CustomObject>
    <fields>
        <fullName>SortOrder__c</fullName>
        <label>SortOrder</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>isMillValley__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mill Valley</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isSerene__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Serene</label>
        <type>Checkbox</type>
    </fields>
    <label>Check List</label>
    <nameField>
        <label>Check List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Check Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Stuff__c.object
<CustomObject>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <label>Stuff</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stuff</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/stuffController.cls
public with sharing class stuffController {
    

    @AuraEnabled(cacheable=false) 
    public static LIST<Stuff__c> getStuff(){
        // System.debug('XXXXXXXXXXXXXXXXXXXXXXXXXXXX: getStuff');
        LIST<Stuff__c> stuffs = [SELECT Name, Completed__c, id
                                 FROM Stuff__c 
                                 WHERE Completed__c=false
                                 ORDER BY Completed__c, CreatedDate desc];
        
        return stuffs;
    }

    @AuraEnabled(cacheable=false) 
    public static LIST<Stuff__c> getStaples(){
        // System.debug('XXXXXXXXXXXXXXXXXXXXXXXXXXXX: getStuff');
        LIST<Stuff__c> stuffs = [SELECT Name, id
                                 FROM Stuff__c 
                                 WHERE isStaple__c=true
                                 ORDER BY StapleOrder__c];
        
        return stuffs;
    }

    @AuraEnabled() 
    public static void addStuffFromStaple(string description){
        try{
            Stuff__c st =  new Stuff__c();
            st.name = description;
            insert st;
        } catch (Exception e) {
            System.debug('Add Stuff From Staple error: ' + e.getMessage());
        }
    }

    @AuraEnabled() // @AuraEnabled(cacheable=true) 
    public static void markDone(id recId){
        // System.debug('XXXXXXXXXXXXXXXXXXXXXXXXXXXX: markDone');
        try{
            Stuff__c st =  [SELECT Name, Completed__c, id
                            FROM Stuff__c 
                            WHERE id= :recId];
            // if (st <> null ){
                st.Completed__c = true;
                update st;
            // }
        } catch (Exception e) {
            System.debug('MARK DONE error: ' + e.getMessage());
        }
    }

    @AuraEnabled(cacheable=false) 
    public static LIST<Check_List__c> getCheckList(){  
        LIST<Check_List__c> cls = [SELECT Name, isMillValley__c, isSerene__c, id
                                 FROM Check_List__c 
                                 WHERE isSerene__c = true
                                 ORDER BY SortOrder__c, Name];
        
        return cls;
    }
    @AuraEnabled(cacheable=false) 
    public static LIST<Check_List__c> getCheckListMV(){  
        LIST<Check_List__c> cls = [SELECT Name, isMillValley__c, isSerene__c, id
                                 FROM Check_List__c 
                                 WHERE isMillValley__c = true
                                 ORDER BY SortOrder__c, Name];
        
        return cls;
    }
}